'use strict';
(() => {
const yes=(id,label)=>({id,label,type:'bool',expected:'yes'});
const no=(id,label)=>({...yes(id,label),expected:'no'});
const num=(id,label,min)=>({id,label,type:'number',min});
const choose=(id,label,options,accept)=>({id,label,type:'select',options,accept});
const base=[no('basicB','特別調剤基本料Ｂを算定している')];
const record=yes('record','必要な実施内容・理由を薬剤服用歴に記録した');
const need=yes('need','患者の状態から治療上・薬学的な支援の必要性を確認した');
const doctor=yes('doctor','処方医の了解を得た');
const sets=[
{id:'residual-post',topic:'residual',rule:17,title:'調剤時残薬調整加算（処方箋受付後の調整）',limits:['在宅患者への処方箋交付前提案（イ）はこの判定の対象外','イ・ロ・ハ・ニの区分、注射薬の製品単位換算、例外的な報告遅延、他項目との全併算定制限は原文確認'],fields:[
yes('management','今回、調剤管理料を算定する'),yes('condition','残薬の外形・保管状況を確認した'),yes('reason','残薬の発生理由と調整の必要性を患者等に確認した'),choose('authority','調整の根拠',[['inquiry','処方医へ照会し変更の了解を得た'],['instruction','処方箋に減量後の情報提供の指示がある'],['none','いずれもない']],['inquiry','instruction']),num('amount','実際に減らした日数・回数相当（頓服・外用は使用回数、隔日は実服薬日数）',1),choose('zero','調整後の処方薬',[['none','ゼロにした薬はない'],['some','一部の薬をゼロにした'],['all','全ての薬をゼロにした']],['none','some']),
{...yes('exception','高額な薬剤による負担軽減の必要性が特に高い、又は薬学的専門的理由がある'),when:a=>validNumber(a.amount)&&Number(a.amount)<7},
{...no('wait','7日分を超えるまで待つことが合理的な状況である'),when:a=>validNumber(a.amount)&&Number(a.amount)<7},
{...yes('next','次回受診日を確認した'),when:a=>validNumber(a.amount)&&Number(a.amount)<7},
{...yes('explain','少量でも調整する必要性を患者等に説明し、概要を薬歴・理由を摘要欄に記録した'),when:a=>validNumber(a.amount)&&Number(a.amount)<7},
yes('report','残薬の状況・理由・交付量・説明内容を原則翌営業日までに処方元へ情報提供した'),yes('prompt','次回受診時に残薬状況を医師へ報告するよう患者に促した'),choose('notebook','手帳への記載',[['done','使用した手帳に記載した'],['unused','今回手帳を使用していない'],['missing','使用したが記載していない']],['done','unused']),record,no('repeat','同じ処方箋受付でこの加算を既に算定している')],extra:a=>a.zero==='some'&&a.authority==='instruction'?[{state:'fail',label:'一部薬剤をゼロにするには、減量後報告の指示だけでなく事前の処方医への照会が必要です（疑義解釈12）。'}]:[]},
{id:'inquiry-change',topic:'inquiry',rule:18,title:'薬学的有害事象等防止加算（処方箋受付後）',limits:['処方箋交付前提案（イ）の判定、患者区分別点数、他項目との全併算定制限は原文確認'],fields:[yes('management','今回、調剤管理料を算定する'),yes('pharmacology','重複投薬・相互作用等の薬学的理由がある'),yes('contact','処方医に連絡・確認した'),yes('changed','残薬調整以外の処方変更が実際に行われた'),yes('analysis','重複投薬の理由を分析し、必要に応じ処方医へ情報提供した（重複がない場合は該当なしとして「はい」）'),record,no('repeat','今回同時に受け付けた処方箋ですでにこの加算を算定している')]},
{id:'support-old',topic:'support',rule:35,title:'外来服薬支援料１（調剤済み薬の整理・注１）',limits:['ブラウンバッグの注２は別経路として原文確認','かかりつけ訪問加算等との併算定制限は原文確認'],fields:[...base,yes('old','処方箋によらず、すでに調剤済みの服用薬を整理した'),yes('difficulty','自己による服薬管理が困難な外来患者である'),yes('request','患者・家族等又は医療機関から求めがあった'),need,doctor,yes('organize','一包化・服薬カレンダー等で実際に薬剤を整理した'),yes('other','他薬局・院内の薬も確認し、必要な重複・相互作用の確認と照会を行った'),yes('background','支援が必要となった背景・理由を分析し、薬学的管理を実施した'),record,no('home','在宅患者訪問薬剤管理指導料を算定している、又は他機関・薬局の薬剤師が訪問薬剤管理指導中である'),no('month','今月すでに外来服薬支援料１を算定した'),no('tech','今回の調剤済み薬への支援自体に調剤基本料等の調剤技術料を請求する'),no('support2','今回、外来服薬支援料２も算定する')]},
{id:'support-pack',topic:'support',rule:36,title:'外来服薬支援料２（今回処方の一包化）',limits:['分割調剤の通算・差額計算、業務委託、特殊な受付の扱いは原文確認','表示点数は通常の１回受付の一包化部分のみ'],fields:[...base,need,doctor,num('kinds','一包化する内服用固形剤の種類数',2),choose('timing','服用時点',[['different','２種類以上の服用時点が異なる'],['same','服用時点は同じ']],['different','same']),yes('unpack','直接の被包から取り出して服用時点ごとに一包化した'),yes('guide','必要な服薬指導を行い、調剤後の服用薬・服薬状況も把握して必要時に処方医へ情報提供する'),record,num('days','一包化した投与日数',1),{...no('split','今回は分割調剤である'),outside:true},no('support1','今回、外来服薬支援料１を算定する'),no('compound','一包化の算定範囲の薬剤に自家製剤加算又は計量混合調剤加算を算定する'),no('repeat','同じ処方箋受付で外来服薬支援料２を既に算定した')],extra:a=>validNumber(a.kinds)&&Number(a.kinds)<3&&a.timing==='same'?[{state:'fail',label:'同じ服用時点のみの場合は３種類以上の内服用固形剤が必要です。'}]:[],points:a=>validNumber(a.days)?(Number(a.days)<=42?Math.ceil(Number(a.days)/7)*34:240):null},
{id:'follow-k',topic:'follow',rule:31,title:'かかりつけ薬剤師フォローアップ加算',limits:['３月に１回・直近６月の履歴は入力者がレセプトで確認','関連医療機関が異なる処方箋の扱い、個別の薬学的妥当性は原文確認'],fields:[...base,yes('k','服薬管理指導料１のイ又は２のイを算定している'),yes('history','直近６月以内に外来支援１・服用薬剤調整支援１/２・残薬調整・有害事象防止のいずれかを算定した'),yes('problem','対象となる残薬等の問題が解消済みではない'),yes('need','患者等の求め又はかかりつけ薬剤師の必要性の判断がある'),yes('consent','事前に聞き取り・指導内容と自己負担額を説明し了解を得た'),yes('bidirectional','個別・双方向の服薬状況、残薬状況の確認と必要な指導を行った'),{id:'dispensed',label:'前回調剤日',type:'date'},{id:'followed',label:'フォローを行った日',type:'date'},{id:'received',label:'関連する医療機関の処方箋を再度受け付けた日（今回の算定日）',type:'date'},yes('appropriate','受診間隔等を考慮し薬学的に適切な時期に実施した'),record,yes('response','体調変化等への必要な医療機関への情報提供・受診勧奨を行い、未解決時は背景の検証と改善策を記録した（対応不要なら「はい」）'),no('conflict','同月に調剤後薬剤管理指導料・在宅患者訪問薬剤管理指導料・居宅療養管理指導費・介護予防居宅療養管理指導費を算定する'),no('multiple','複数薬局で服薬管理指導料１のイ又は２のイを算定している'),no('repeat','３月に１回の算定上限を超える')],extra:a=>['dispensed','followed','received'].every(k=>validDate(a[k]))?[{state:a.dispensed<a.followed&&a.followed<a.received?'pass':'fail',label:'フォロー日は前回調剤日より後、関連処方箋の再受付日より前である必要があります（両当日を除く）。'}]:[]},
{id:'poly-one',topic:'poly',rule:38,title:'服用薬剤調整支援料１',limits:['１年以内の再算定は前回減薬後からさらに２種類以上の減少が必要','薬剤数の臨床的な分類、他の点数・施設区分との制限は原文確認'],fields:[num('before','開始から４週間以上経過した内服薬の種類数（頓服は除く）',6),yes('proposal','患者の意向、服薬状況、副作用等を検討して処方医へ減薬を提案した'),num('reduced','対象となる内服薬の減少種類数（配合剤・内服以外への置換による減少は除く）',2),num('proposed','減った薬のうち、この薬局の薬剤師が提案した種類数',1),num('weeks','減薬状態が継続した週数',4),yes('summary','医療機関名・調整前後の種類数を摘要欄に記載した'),yes('result','検討内容と患者の意向を薬歴に記録し、調整結果の情報を保存した'),choose('repeat','１年以内の算定歴',[['none','算定していない'],['further','算定したが、前回減薬後からさらに２種類以上減った'],['same','算定した。追加の２種類以上の減少はない']],['none','further'])],extra:a=>validNumber(a.proposed)&&validNumber(a.reduced)&&Number(a.proposed)>Number(a.reduced)?[{state:'unknown',label:'入力矛盾：提案して減った種類数が全減少種類数を超えています。修正してください。'}]:[]},
{id:'poly-two',topic:'poly',rule:38,title:'服用薬剤調整支援料２（開始時期・主な要件）',limits:['６領域の総合評価内容、指定研修・様式、結果伝達、在宅患者のかかりつけ同意は原文確認','開始日以後でも、このチェックのみでは全要件充足とはなりません'],fields:[{id:'claim',label:'算定予定日',type:'date',after:'2027-06-01'},...base,yes('trained','指定研修を修了したかかりつけ薬剤師が実施した'),num('institutions','内服薬を処方する医療機関数',2),num('kinds','処方されている内服薬の合計種類数',6),yes('request','患者又は家族等から求めがあった'),yes('evaluation','継続的・一元的に把握し、必要性を判断して服用薬剤総合評価を行った'),yes('written','処方医に文書で調整を提案した'),yes('consent','事前に総合評価の意義と自己負担額を説明し了解を得た'),no('relation','特別調剤基本料Ａで、特別な関係のある医療機関への情報提供である'),no('six','同じ患者で６月に１回の上限を超える'),num('capacity','この算定を含む、実施薬剤師の今月の算定回数',1)],extra:a=>validNumber(a.capacity)&&Number(a.capacity)>4?[{state:'fail',label:'かかりつけ薬剤師１人につき月４回までです。'}]:[]}
];
function validNumber(v){return v!==''&&v!==undefined&&Number.isInteger(Number(v))&&Number(v)>=0;}
function validDate(v){return typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&!isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v;}
function evaluate(set,a={}){const results=set.fields.filter(f=>!f.when||f.when(a)).map(f=>{const v=a[f.id];let state='unknown';if(f.type==='bool'&&['yes','no'].includes(v))state=v===f.expected?'pass':'fail';if(f.type==='select'&&f.options.some(o=>o[0]===v))state=f.accept.includes(v)?'pass':'fail';if(f.type==='number'&&validNumber(v))state=Number(v)>=f.min?'pass':'fail';if(f.type==='date'&&validDate(v))state=!f.after||v>=f.after?'pass':'fail';if(f.outside&&state==='fail')return {id:f.id,label:f.label+'：この経路は判定範囲外のため原文確認',state:'unknown'};return {id:f.id,label:f.label,state};}).concat(set.extra?.(a)||[]);return {results,state:results.some(r=>r.state==='fail')?'fail':results.some(r=>r.state==='unknown')?'unknown':'pass',points:set.points?.(a)??null};}
const api={sets,evaluate,validDate};if(typeof module!=='undefined'&&module.exports){module.exports=api;return;}window.FeeConditions=api;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const answers={};
api.mount=(root,topic,rules,data)=>{const relevant=sets.filter(s=>s.topic===topic&&rules.includes(s.rule));root.innerHTML=relevant.length?`<h3>条件を入力して判定する</h3><p>確認済みの事実を入力してください。未確認は未確認のまま扱います。回答はこの画面内のみで使用し、再読み込みで消去します。</p>`:'<p class="notice">この場面の対話式条件判定は未実装です。下の公式要件・具体例で確認できます。</p>';for(const s of relevant){const a=answers[s.id]||(answers[s.id]={}),box=document.createElement('details');box.className='condition-box';box.innerHTML=`<summary>${esc(s.title)}</summary><div class="condition-fields"></div><div class="condition-result" role="status" aria-live="polite"></div><h4>この判定の範囲外・原文で確認する事項</h4><ul>${s.limits.map(l=>`<li>${esc(l)}</li>`).join('')}</ul>`;root.append(box);const fields=box.querySelector('.condition-fields'),result=box.querySelector('.condition-result');function update(){for(const f of s.fields){const label=fields.querySelector('[data-field="'+f.id+'"]');label.hidden=!!f.when&&!f.when(a);}const e=evaluate(s,a),labels={pass:'入力した範囲の条件を満たしています',fail:'満たしていない条件があります',unknown:'未確認・入力の確認が必要な条件があります'};result.className='condition-result '+e.state;result.innerHTML=`<strong>${labels[e.state]}</strong><p>確認済み ${e.results.filter(r=>r.state==='pass').length} / 今回の確認条件 ${e.results.length}。算定の確定には下記の範囲外事項も確認してください。</p><ul>${e.results.filter(r=>r.state!=='pass').map(r=>`<li>${r.state==='fail'?'不適合':'未確認'}：${esc(r.label)}</li>`).join('')}</ul>${e.state==='pass'&&e.points!==null?`<p>通常受付の一包化部分の参考点数：<strong>${e.points}点</strong></p>`:''}`;}
fields.innerHTML=s.fields.map(f=>`<label data-field="${f.id}" for="${s.id}-${f.id}"><span>${esc(f.label)}</span>${['number','date'].includes(f.type)?`<input id="${s.id}-${f.id}" data-id="${f.id}" type="${f.type}" ${f.type==='number'?'min="0" step="1"':''} value="${esc(a[f.id]||'')}">`:`<select id="${s.id}-${f.id}" data-id="${f.id}"><option value="">未確認</option>${(f.type==='bool'?[['yes','はい'],['no','いいえ']]:f.options).map(o=>`<option value="${o[0]}" ${a[f.id]===o[0]?'selected':''}>${esc(o[1])}</option>`).join('')}</select>`}</label>`).join('');fields.addEventListener('change',ev=>{if(ev.target.dataset.id){a[ev.target.dataset.id]=ev.target.value;update();}});const source=data.rules.find(r=>r.id==='rule-'+s.rule);const link=document.createElement('a');link.href=source.url;link.target='_blank';link.rel='noopener';link.textContent='根拠：'+source.title+'（PDF '+source.page+'ページ）';box.append(link);if(s.id==='residual-post'){const qa=document.createElement('a');qa.href='https://www.mhlw.go.jp/content/12400000/001744953.pdf#page=8';qa.target='_blank';qa.rel='noopener';qa.textContent=' ／ ゼロ調整の根拠：疑義解釈12・問３';box.append(qa);}update();}};
})();
