'use strict';
(()=>{
const restrictions=[
[30,51,'同じ情報提供',30],[26,51,'同じ情報提供',26],[39,51,'同じ情報提供',39],[53,51,'同じ情報提供',53],
[35,36,'同じ支援・算定機会',36],[31,39,'同じ月',31],[31,41,'同じ月',31],
[54,49,'同じ日',54],[54,53,'同じ日',54],[55,49,'同じ日',55],[55,53,'同じ日',55],[55,54,'同じ日',55],
[53,35,'同じ算定日',53],[28,29,'同じ算定機会',29],[44,45,'同じ算定機会',45],[42,43,'同じ患者への算定',43]
];
function pairs(ids){const out=[];for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++){const rule=restrictions.find(r=>(r[0]===ids[i]&&r[1]===ids[j])||(r[1]===ids[i]&&r[0]===ids[j]));out.push({a:ids[i],b:ids[j],rule});}return out;}
function assessPair(pair,answer){if(!pair.rule)return {state:'unknown',text:'この組み合わせの横断判定は未実装です。原文・併算定表で確認してください。'};if(answer==='same')return {state:'fail',text:pair.rule[2]+'に該当するため、記載の併算定制限に該当します。'};if(answer==='different')return {state:'unknown',text:'この制限の条件には該当しませんが、他の制限を含む併算定可否は未確定です。'};return {state:'unknown',text:pair.rule[2]+'かどうかを確認してください。'};}
if(typeof module!=='undefined'&&module.exports){module.exports={restrictions,pairs,assessPair};return;}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
fetch('./data.json').then(r=>{if(!r.ok)throw Error();return r.json();}).then(data=>{
const sets=window.FeeConditions.sets,root=document.getElementById('coverage-panel');const rule=id=>data.rules.find(r=>r.id==='rule-'+id);
root.innerHTML=`<h2>対応状況と併算定の確認</h2><p>条件判定 ${sets.length}経路。設問数は網羅率ではありません。全項目の原文と判定の対応範囲を確認できます。</p><details><summary>元表の全項目・略号と原文の対応を見る（${data.items.length}項目）</summary><div class="coverage-scroll"><table class="coverage-table"><thead><tr><th>項目・略号</th><th>対応する公式原文</th><th>確認上の注意</th></tr></thead><tbody>${data.items.map(item=>`<tr><th>${esc(item.name)}<br>${esc(item.abbr)}</th><td>${item.rules.map(id=>{const r=data.rules.find(r=>r.id===id);return r?`<a href="${esc(r.url)}" target="_blank" rel="noopener">${esc(r.title)}</a><br>`:'';}).join('')}</td><td>原文への対応付けです。区分・点数・全要件の検証完了を意味しません。</td></tr>`).join('')}</tbody></table></div></details><details><summary>公式条文別の対応状況を見る（元表にない項目も含む）</summary><div class="coverage-scroll"><table class="coverage-table"><thead><tr><th>公式項目</th><th>原文</th><th>条件判定</th><th>未対応・原文確認</th></tr></thead><tbody>${data.rules.map(r=>{const ss=sets.filter(s=>'rule-'+s.rule===r.id);return `<tr><th>${esc(r.title)}</th><td><a href="${esc(r.url)}" target="_blank" rel="noopener">収録済み</a></td><td>${ss.length?ss.length+'経路・一部条件を実装':'未実装'}</td><td>${ss.length?ss.map(s=>`<details><summary>${esc(s.title)}</summary><ul>${s.limits.map(l=>`<li>${esc(l)}</li>`).join('')}</ul></details>`).join(''):'対象患者・実施要件・例外・回数・併算定の条件判定が未実装'}</td></tr>`;}).join('')}</tbody></table></div></details><details><summary>複数候補の併算定制限を確認する</summary><p>同じ患者の候補を２つ以上選んでください。各組み合わせについて、同日・同月・同じ報告などを個別に確認します。</p><div id="cross-options" class="cross-options">${[...new Set(sets.map(s=>s.rule).concat([41,49]))].sort((a,b)=>a-b).map(id=>`<label><input type="checkbox" value="${id}"> ${esc(rule(id).title)}</label>`).join('')}</div><div id="cross-results" aria-live="polite"></div></details>`;
const selected=new Set(),answers={};function renderPairs(){document.getElementById('cross-results').innerHTML=pairs([...selected]).map(p=>{const key=[p.a,p.b].sort((a,b)=>a-b).join('-'),result=assessPair(p,answers[key]);return `<article class="card"><h3>${esc(rule(p.a).title)} × ${esc(rule(p.b).title)}</h3>${p.rule?`<label>${esc(p.rule[2])}ですか？<select data-pair="${key}"><option value="">未確認</option><option value="same" ${answers[key]==='same'?'selected':''}>はい</option><option value="different" ${answers[key]==='different'?'selected':''}>いいえ</option></select></label>`:''}<p class="notice">${esc(result.text)}</p>${p.rule?`<a href="${esc(rule(p.rule[3]).url)}" target="_blank" rel="noopener">制限の根拠</a> ／ <a href="https://www.mhlw.go.jp/content/12400000/001665294.pdf" target="_blank" rel="noopener">点数表の注記</a>`:''}</article>`;}).join('')||'<p>候補を２つ以上選ぶと結果を表示します。</p>';}
document.getElementById('cross-options').addEventListener('change',e=>{const id=Number(e.target.value);e.target.checked?selected.add(id):selected.delete(id);renderPairs();});document.getElementById('cross-results').addEventListener('change',e=>{if(e.target.dataset.pair){answers[e.target.dataset.pair]=e.target.value;renderPairs();}});renderPairs();
}).catch(()=>{document.getElementById('coverage-panel').textContent='対応状況を読み込めませんでした。再読み込みしてください。';});
})();
